<?php
/**
 * @copyright Copyright (c) 2025 Magebit (https://magebit.com/)
 * @author    <info@magebit.com>
 * @license   GNU General Public License ("GPL") v3.0
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/** @var \Magento\Catalog\Block\Product\View $block */
?>
<?php $product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($product->isSaleable()) :?>
    <?php $stockQty = (int)$product->getExtensionAttributes()->getStockItem()->getQty(); ?>
<div class="box-tocart" data-mage-init='{"qty": {}}'>
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <button type="button" class="qty-decrease">-</button>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
            <button type="button" id="add-qty" class="qty-increase">+</button>
            <div class="stock-info">
                <img class="stock-checkmark"
                     src="<?= $block->getViewFileUrl('images/checkmark.svg'); ?>"
                <h4 class="stock-heading">IN STOCK </h4>
                <span class="stock-text">
                    <?= __(' %1 items in stock', $stockQty) ?>
                </span>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
