<?php
/**
 * @copyright Copyright (c) 2025 Magebit (https://magebit.com/)
 * @author    <info@magebit.com>
 * @license   GNU General Public License ("GPL") v3.0
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/** @var Template $block */

use Magento\Framework\View\Element\Template;

?>

<div class="qty-wrapper">
    <button type="button" class="qty-decrease">-</button>
    <input type="number" id="qty" name="qty" value="1" min="1" class="qty-input" />
    <button type="button" class="qty-increase">+</button>
</div>

