<?php
/**
 * @copyright Copyright (c) 2025 Magebit (https://magebit.com/)
 * @author    <info@magebit.com>
 * @license   GNU General Public License ("GPL") v3.0
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/** @var $block \Magebit\Orders\Block\Product\View\Stock */
?>

<div class="product-stock">
    <span><?= $block->getAvailableStock() ?> items available</span>
</div>
