<?php
/** @var \Magento\Framework\View\TemplateEngineInterface $this */
/** @var MageMastery\PageListWidget\Block\Page\Widget\PageList $block */
/** @var \Magento\Csp\Api\InlineUtilInterface $csp */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<h3><?= $escaper->escapeHtml($block->getTitle()) ?></h3>
<!--<h3>--><?php //= $escaper->escapeHtml($block->getSelectedPages()) ?><!--</h3>-->
